
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

  username: julie
  password: julie

development:
  <<: *default
  database: order_it_dev

production:
  <<: *default
  database: order_it_prod
test: &test
  <<: *default
  database: order_it_test

